# Generated by Django 5.2 on 2025-05-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('date', models.DateField(auto_now_add=True, verbose_name='投稿日時')),
                ('text', models.TextField(max_length=1000, verbose_name='今日の出来事')),
                ('mood_happy', models.BooleanField(default=False, verbose_name='楽しい')),
                ('mood_sad', models.BooleanField(default=False, verbose_name='悲しい')),
                ('mood_angry', models.BooleanField(default=False, verbose_name='怒っている')),
                ('mood_anxious', models.BooleanField(default=False, verbose_name='不安')),
                ('mood_calm', models.BooleanField(default=False, verbose_name='落ち着いている')),
                ('mood_exhausted', models.BooleanField(default=False, verbose_name='疲れている')),
                ('image', models.ImageField(blank=True, null=True, upload_to='diary/images/', verbose_name='画像')),
            ],
        ),
    ]
