# Generated by Django 5.2.1 on 2025-05-16 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_comment_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='diary',
            table='diary',
        ),
    ]
