# Generated by Django 5.2.1 on 2025-05-21 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_alter_diary_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='投稿日時'),
        ),
    ]
