# Generated by Django 5.2.1 on 2025-05-21 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_alter_diary_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='encouragement_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
