# Generated by Django 5.2 on 2025-05-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': '同一のユーザー名が既に登録されています'}, max_length=20, unique=True, verbose_name='ユーザー名'),
        ),
    ]
